package Controllers;

import java.net.URL;
import java.util.ResourceBundle;

import org.w3c.dom.events.MouseEvent;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;


public class controler_accueil implements Initializable{
	public class controleraccueil {

		@FXML
		private AnchorPane root;
		private Parent fxml;
		
		@FXML
		public void Enregistrer_Client(ActionEvent event) {
			// TODO Autogenerated 
			try {
				fxml=FXMLLoader.load(getClass().getResource("/interface/Enregistrement1.fxml"));
				
				root.getChildren().removeAll();
				root.getChildren().setAll(fxml);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
		
		
		@FXML
		public void Enregistrement_Reservation(ActionEvent event) {
			
			// TODO Autogenerated
			try {
				fxml=FXMLLoader.load(getClass().getResource("/interface/Enregistrement2.fxml"));
				
				root.getChildren().removeAll();
				root.getChildren().setAll(fxml);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
		
		
		@FXML
		public void nos_compagnies(ActionEvent event) {
			// TODO Autogenerated
			try {
				fxml=FXMLLoader.load(getClass().getResource("/interfaces/compagnies.fxml"));
				
				root.getChildren().removeAll();
				root.getChildren().setAll(fxml);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
		
		
		@FXML
		public void Caisse(ActionEvent event) {
			// TODO Autogenerated
			try {
				fxml=FXMLLoader.load(getClass().getResource("/interfaces/caisse_principale.fxml"));
				
				root.getChildren().removeAll();
				root.getChildren().setAll(fxml);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
		
		@FXML
		public void Accueil(ActionEvent event) {
			// TODO Autogenerated 
			try {
				fxml=FXMLLoader.load(getClass().getResource("/interfaces/Accueil.fxml"));
				
				root.getChildren().removeAll();
				root.getChildren().setAll(fxml);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
		}
		
	   
	}

	public void start(Stage arg0) throws Exception {
		// TODO Auto-generated method stub
		
	}



	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
